'use strict';
(() => {
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function runtimeSource(){return `
const P=window.DERPEDIT_PROJECT;let roomId=P.startRoom||P.rooms[0].id,G=null,keys={},cam={x:0,y:0};
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),ui=document.getElementById('ui');
function size(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',size);size();
const clone=v=>JSON.parse(JSON.stringify(v)),hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function room(){return P.rooms.find(r=>r.id===roomId)}
function start(id,preserve=false){roomId=id||roomId;const r=room(),O=clone(r.objects||[]);let pl=O.find(o=>o.type==='being'&&o.beingRole==='player')||{id:'player',type:'being',beingRole:'player',x:60,y:60,w:42,h:42,color:'#278cff',speed:220,health:100};if(!O.includes(pl))O.push(pl);const sp=O.find(o=>o.behavior==='spawn');if(sp){pl.x=sp.x;pl.y=sp.y}G={r,O,pl,last:performance.now(),wave:0,waveActive:false};buttons();if(r.waveEnabled)spawnWave(1)}
function enemies(){return G.O.filter(o=>o.type==='being'&&o.beingRole==='enemy'&&!o.destroyed)}
function spawnWave(n){const w=G.r.waves?.[n-1];if(!w)return;G.wave=n;G.waveActive=true;for(const en of w.entries||[]){const t=G.r.objects.find(o=>o.id===en.enemyId);if(!t)continue;for(let i=0;i<(en.count||1);i++){const e=clone(t);e.id=t.id+'_w'+n+'_'+i+'_'+Date.now();e.x=40+Math.random()*Math.max(20,(G.r.width||innerWidth)-80);e.y=40+Math.random()*Math.max(20,(G.r.height||innerHeight)-80);e.speed=Number(en.speed)||e.speed;e.destroyed=false;G.O.push(e)}}}
function buttons(){ui.innerHTML='';for(const o of G.O.filter(o=>o.type==='button'&&o.layer==='ui')){const b=document.createElement('button');b.textContent=o.text||o.name;b.style.cssText='position:absolute;left:'+o.x+'px;top:'+o.y+'px;width:'+o.w+'px;height:'+o.h+'px;background:'+o.color;b.onclick=()=>{if(o.action==='goto')start(o.targetRoom,true);if(o.action==='restart')start(roomId,true)};ui.appendChild(b)}}
function update(dt){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),l=Math.hypot(dx,dy)||1;G.pl.x+=dx/l*G.pl.speed*dt;G.pl.y+=dy/l*G.pl.speed*dt;if(!G.r.infinite){G.pl.x=Math.max(0,Math.min((G.r.width||innerWidth)-G.pl.w,G.pl.x));G.pl.y=Math.max(0,Math.min((G.r.height||innerHeight)-G.pl.h,G.pl.y))}for(const e of enemies()){let x=G.pl.x-e.x,y=G.pl.y-e.y,z=Math.hypot(x,y)||1;e.x+=x/z*(e.speed||100)*dt;e.y+=y/z*(e.speed||100)*dt;if(hit(G.pl,e))G.pl.health-=Number(e.damage||10)*dt}if(G.waveActive&&!enemies().length){G.waveActive=false;setTimeout(()=>{if(G.r.waves?.[G.wave])spawnWave(G.wave+1)},700)}}
function draw(){const r=G.r,w=innerWidth,h=innerHeight;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.fillStyle=P.background||'#202633';ctx.fillRect(0,0,w,h);if(r.cameraMode!=='fixed'){let tx=G.pl.x+G.pl.w/2-w/2,ty=G.pl.y+G.pl.h/2-h/2;if(!r.infinite&&r.cameraMode!=='infinite'){tx=Math.max(0,Math.min((r.width||w)-w,tx));ty=Math.max(0,Math.min((r.height||h)-h,ty))}cam.x+=(tx-cam.x)*.14;cam.y+=(ty-cam.y)*.14}else cam={x:0,y:0};ctx.save();ctx.translate(-cam.x,-cam.y);for(const o of G.O){if(o.destroyed||o.collected||o.layer==='ui'||o.behavior==='spawn'||o.type==='button'||o.type==='scriptobject')continue;ctx.save();ctx.globalAlpha=(o.opacity??100)/100;ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate((o.rotation||0)*Math.PI/180);const a=P.assets?.find(a=>a.id===o.assetId);if(a){o._im=o._im||new Image();o._im.src=a.data;ctx.imageSmoothingEnabled=false;ctx.drawImage(o._im,-o.w/2,-o.h/2,o.w,o.h)}else{ctx.fillStyle=o.color||'#fff';if(o.type==='being'){ctx.beginPath();ctx.ellipse(0,0,o.w/2,o.h/2,0,0,7);ctx.fill()}else ctx.fillRect(-o.w/2,-o.h/2,o.w,o.h)}ctx.restore()}ctx.restore();document.getElementById('hud').textContent='Health: '+Math.max(0,Math.ceil(G.pl.health))+(r.waveEnabled?' | Wave: '+G.wave:'')}
let mpClient=null,mpChannel=null,mpRemote=new Map(),mpId='p_'+Math.random().toString(36).slice(2),mpLast=0;
async function mpConnect(code,name){if(!P.multiplayer?.enabled)return;code=String(code||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(!code)return;mpClient=supabase.createClient(P.multiplayer.url,P.multiplayer.key);mpChannel=mpClient.channel('derpedit-'+code,{config:{presence:{key:mpId},broadcast:{self:false}}});mpChannel.on('broadcast',{event:'player'},({payload})=>{if(payload?.id!==mpId)mpRemote.set(payload.id,payload)});await mpChannel.subscribe(async st=>{if(st==='SUBSCRIBED'){await mpChannel.track({id:mpId,name});document.getElementById('multiplayer').style.display='none'}})}
function mpTick(){if(!mpChannel||!G)return;const now=performance.now();if(now-mpLast>80){mpLast=now;mpChannel.send({type:'broadcast',event:'player',payload:{id:mpId,name:document.getElementById('mpName')?.value||'Player',room:roomId,x:G.pl.x,y:G.pl.y,w:G.pl.w,h:G.pl.h,color:G.pl.color}})}ctx.save();ctx.translate(-cam.x,-cam.y);for(const r of mpRemote.values()){if(r.room!==roomId)continue;ctx.globalAlpha=.75;ctx.fillStyle=r.color||'#5de0e6';ctx.fillRect(r.x,r.y,r.w||42,r.h||42)}ctx.restore()}
if(P.multiplayer?.enabled){document.getElementById('mpHost').onclick=()=>document.getElementById('mpCode').value=Math.random().toString(36).slice(2,8).toUpperCase();document.getElementById('mpJoin').onclick=()=>mpConnect(document.getElementById('mpCode').value,document.getElementById('mpName').value).catch(e=>document.getElementById('mpStatus').textContent=e.message)}
function frame(t){if(!G)return;const dt=Math.min(.033,(t-G.last)/1000);G.last=t;update(dt);draw();mpTick();requestAnimationFrame(frame)}addEventListener('keydown',e=>keys[e.key.toLowerCase()]=1);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);start();requestAnimationFrame(frame);
`;}
  function indexSource(){const data=JSON.stringify(p).replace(/</g,'\\u003c');const mp=p.multiplayer?.enabled?`<div id="multiplayer"><div class="mpBox"><h2>Multiplayer</h2><input id="mpName" placeholder="Player name" value="Player"><input id="mpCode" maxlength="6" placeholder="JOIN CODE"><div><button id="mpHost">Create Code</button><button id="mpJoin">Join</button></div><small id="mpStatus">Not connected</small></div></div><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"><\\/script>`:'';return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.name)}</title><link rel="stylesheet" href="css/game.css"></head><body><canvas id="game"></canvas><div id="hud"></div><div id="ui"></div>${mp}<script>window.DERPEDIT_PROJECT=${data};<\\/script><script src="js/game.js"><\\/script></body></html>`}
  const css=`html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000;font-family:system-ui;color:white}#game{display:block}#hud{position:fixed;left:12px;top:12px;background:#0009;padding:8px 10px;border-radius:8px}#ui{position:fixed;inset:0;pointer-events:none}#ui button{pointer-events:auto;color:white;border:1px solid #ffffff55;border-radius:8px;font-weight:700}#multiplayer{position:fixed;inset:0;background:#0009;display:grid;place-items:center;z-index:100}.mpBox{width:min(380px,86vw);background:#17202f;border:1px solid #61708f;border-radius:14px;padding:18px;display:grid;gap:10px}.mpBox input,.mpBox button{padding:10px;box-sizing:border-box}.mpBox>div{display:flex;gap:8px}.mpBox>div>*{flex:1}`;
  async function exportZip(){if(!window.JSZip)return alert('JSZip did not load. Check your internet connection once, then retry.');const z=new JSZip();z.file('index.html',indexSource());z.folder('css').file('game.css',css);z.folder('js').file('game.js',runtimeSource());z.file('README.md','# '+p.name+'\\n\\nGitHub Pages-ready export from Derpedit v1.0. Upload every file and folder to a repository, then enable GitHub Pages from the repository settings.\\n');const blob=await z.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(p.name||'Derpedit-Game').replace(/[^a-z0-9_-]+/gi,'-')+'-github.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
  window.DerpeditExporter={exportZip,indexSource,runtimeSource};
})();
