'use strict';
(() => {
  const q=id=>document.getElementById(id);
  let client=null;

  const defaults=()=>({
    enabled:false,url:'',key:'',table:'derpedit_leaderboard',
    playerName:'Player',values:['Score']
  });

  function config(){
    p.online??=defaults();
    p.online.values??=['Score'];
    return p.online;
  }

  function cleanIdentifier(value,fallback){
    const cleaned=String(value||'').trim().replace(/[^a-zA-Z0-9_]/g,'');
    return cleaned||fallback;
  }

  function allowedValue(name){
    return config().values.map(v=>v.toLowerCase()).includes(String(name).toLowerCase());
  }

  function getClient(){
    const c=config();
    if(!c.enabled)throw new Error('Online is disabled for this project.');
    if(!c.url||!c.key)throw new Error('Supabase URL and Publishable/anon key are required.');
    if(!window.supabase?.createClient)throw new Error('Supabase library did not load. Check the internet connection.');
    client??=window.supabase.createClient(c.url,c.key,{auth:{persistSession:false,autoRefreshToken:false}});
    return client;
  }

  function resetClient(){client=null}

  async function submitScore(valueName,value,playerName=config().playerName){
    const c=config();
    if(!c.enabled)return {offline:true};
    if(!allowedValue(valueName))throw new Error(`"${valueName}" is not in Online value names.`);
    const numeric=Number(value);
    if(!Number.isFinite(numeric))throw new Error('Leaderboard value must be a finite number.');
    const table=cleanIdentifier(c.table,'derpedit_leaderboard');
    const row={
      game_id:String(p.name||'Derpedit Game').slice(0,80),
      value_name:String(valueName).slice(0,60),
      player_name:String(playerName||'Player').slice(0,40),
      score:numeric
    };
    const {data,error}=await getClient().from(table).insert(row).select('id,game_id,value_name,player_name,score,created_at').single();
    if(error)throw error;
    return data;
  }

  async function getLeaderboard(valueName,limit=10){
    const c=config();
    if(!c.enabled)return [];
    if(!allowedValue(valueName))throw new Error(`"${valueName}" is not in Online value names.`);
    const table=cleanIdentifier(c.table,'derpedit_leaderboard');
    const safeLimit=Math.max(1,Math.min(100,Math.floor(Number(limit)||10)));
    const {data,error}=await getClient()
      .from(table)
      .select('player_name,score,created_at')
      .eq('game_id',String(p.name||'Derpedit Game').slice(0,80))
      .eq('value_name',String(valueName).slice(0,60))
      .order('score',{ascending:false})
      .limit(safeLimit);
    if(error)throw error;
    return data||[];
  }

  async function test(){
    const box=q('onlineStatus');
    try{
      box.textContent='Testing connection...';
      const c=config(),table=cleanIdentifier(c.table,'derpedit_leaderboard');
      const {error}=await getClient().from(table).select('id').limit(1);
      if(error)throw error;
      box.textContent='Connected successfully. The leaderboard table is readable.';
    }catch(error){
      box.textContent='Connection failed: '+(error.message||error);
    }
  }

  function fill(){
    const c=config();
    q('onlineEnabled').checked=!!c.enabled;
    q('supabaseUrl').value=c.url||'';
    q('supabaseKey').value=c.key||'';
    q('leaderboardTable').value=c.table||'derpedit_leaderboard';
    q('onlinePlayerName').value=c.playerName||'Player';
    q('onlineValueNames').value=(c.values||['Score']).join(', ');
    q('onlineStatus').textContent=c.enabled?'Online is enabled for this project.':'Online is optional and currently disabled.';
  }

  function save(){
    checkpoint();
    const names=q('onlineValueNames').value.split(',').map(v=>v.trim()).filter(Boolean);
    p.online={
      enabled:q('onlineEnabled').checked,
      url:q('supabaseUrl').value.trim(),
      key:q('supabaseKey').value.trim(),
      table:cleanIdentifier(q('leaderboardTable').value,'derpedit_leaderboard'),
      playerName:q('onlinePlayerName').value.trim()||'Player',
      values:[...new Set(names.length?names:['Score'])]
    };
    resetClient();
    render();
    q('onlineStatus').textContent='Online settings saved into this project.';
  }

  const setupSql=`-- Derpedit optional public leaderboard
create table if not exists public.derpedit_leaderboard (
  id bigint generated by default as identity primary key,
  game_id text not null check (char_length(game_id) between 1 and 80),
  value_name text not null check (char_length(value_name) between 1 and 60),
  player_name text not null check (char_length(player_name) between 1 and 40),
  score double precision not null,
  created_at timestamptz not null default now()
);

alter table public.derpedit_leaderboard enable row level security;

create policy "Public leaderboard read"
on public.derpedit_leaderboard
for select
to anon, authenticated
using (true);

create policy "Public leaderboard submit"
on public.derpedit_leaderboard
for insert
to anon, authenticated
with check (
  char_length(game_id) between 1 and 80
  and char_length(value_name) between 1 and 60
  and char_length(player_name) between 1 and 40
  and score between -1000000000000 and 1000000000000
);

create index if not exists derpedit_leaderboard_rank
on public.derpedit_leaderboard (game_id, value_name, score desc);`;

  q('onlineBtn').onclick=()=>{fill();q('onlineModal').classList.remove('hidden')};
  q('closeOnline').onclick=()=>q('onlineModal').classList.add('hidden');
  q('saveOnline').onclick=save;
  q('testOnline').onclick=async()=>{save();await test()};
  q('copySupabaseSql').onclick=async()=>{
    try{await navigator.clipboard.writeText(setupSql);q('onlineStatus').textContent='Setup SQL copied.'}
    catch{q('onlineStatus').textContent='Could not access clipboard. Use SUPABASE_SETUP.sql from the ZIP.'}
  };

  window.DerpeditOnline={submitScore,getLeaderboard,get config(){return {...config(),key:config().key?'(saved)':''}}};
})();
