-- Derpedit v0.7.1 optional leaderboard setup
-- Run this in the Supabase SQL Editor.

create table if not exists public.derpedit_leaderboard (
  id bigint generated by default as identity primary key,
  game_id text not null check (char_length(game_id) between 1 and 80),
  value_name text not null check (char_length(value_name) between 1 and 60),
  player_name text not null check (char_length(player_name) between 1 and 40),
  score double precision not null,
  created_at timestamptz not null default now()
);

alter table public.derpedit_leaderboard enable row level security;

create policy "Public leaderboard read"
on public.derpedit_leaderboard
for select
to anon, authenticated
using (true);

create policy "Public leaderboard submit"
on public.derpedit_leaderboard
for insert
to anon, authenticated
with check (
  char_length(game_id) between 1 and 80
  and char_length(value_name) between 1 and 60
  and char_length(player_name) between 1 and 40
  and score between -1000000000000 and 1000000000000
);

create index if not exists derpedit_leaderboard_rank
on public.derpedit_leaderboard (game_id, value_name, score desc);
